Fix -Werror=format-security errors
There are many errors of the form:
../git/secure.c:303:31: error: format not a string literal and no
format arguments [-Werror=format-security]
         xenstore_write_int(0, state_node);

Fix those up mechanically by change 'state_node' to '"%s", state_node'.
The exception is switcher_get_slot_type which was changed to drop the
sprintf call and just provide the format and argument to xenstore_read.

OXT-1697

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>