Fix -Werror=unused-result errors
../git/keymap.c: In function 'get_configured_keymap':
../git/keymap.c:76:5: error: ignoring return value of 'fgets',
declared with attribute warn_unused_result [-Werror=unused-result]
     fgets(line, sizeof(line), f);

Error out on a failed fgets() call.

../git/input.c: In function 'input_led':
../git/input.c:1855:13: error: ignoring return value of 'write',
declared with attribute warn_unused_result [-Werror=unused-result]
             write(input_dev.fds[i], &ev, sizeof(struct input_event));

input_led is a void function, so just ignore the return value from
write.  We don't have a meaningful way to return an error.  A void cast
is insufficient to silence the error, but the additional negation does
the trick.

OXT-1697

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>